name: "predictor_2"
backend: "python"
max_batch_size: 16

input [
  {
    name: "FEATURES"
    data_type: TYPE_FP32
    dims: [ 37 ]
  }
]
output [
  {
    name: "LABELS"
    data_type: TYPE_INT64
    dims: [ 1 ]
    reshape: { shape: [ ] }
  }
]

instance_group [{ count: 1 kind: KIND_CPU }]
parameters: [
  {
    key: "input_name"
    value: {
      string_value: "FEATURES"
    }
  },
  {
    key: "output_name"
    value: {
      string_value: "LABELS"
    }
  },
  {
    key: "EXECUTION_ENV_PATH",
    value: {string_value: "/models/conda-pack.tar.gz"}
  }
]