FROM python:3.8.10-slim
RUN apt-get update && apt-get install -y ffmpeg make ca-certificates curl gnupg
RUN pip install -U pip & pip install pipenv
WORKDIR "/root/src"
COPY [ "../Pipfile", "../Pipfile.lock", "./" ]
RUN pipenv install --system --deploy