FROM python:3.8.10-slim
RUN apt-get update && apt-get install -y ffmpeg make ca-certificates curl gnupg
RUN pip install -U pip==23.2.1 && pip install pipenv==2023.7.23
WORKDIR "/root/src"
COPY [ "../Pipfile", "../Pipfile.lock", "./" ]
RUN pipenv install --system --deploy