FROM ghcr.io/mlflow/mlflow:v2.5.0
EXPOSE 5001
COPY [ "../src/scripts/run_mlflow.sh", "/scripts/" ]
RUN chmod +x /scripts/run_mlflow.sh
RUN apt update && apt install -y gcc libpq-dev
RUN pip install --upgrade pip && pip install awscli==1.29.25 psycopg2==2.8.5 boto3==1.28.25
