FROM nvcr.io/nvidia/tritonserver:23.01-py3-sdk
RUN pip3 install --upgrade pip && pip3 install awscli==1.29.25 click==8.1.6 prefect==2.11.3 boto3==1.28.25 black==23.7.0 coloredlogs==15.0.1
ENV PREFECT_KEY=""
ENV PREFECT_WORKSPACE=""
RUN prefect cloud login --key ${PREFECT_KEY} --workspace ${PREFECT_WORKSPACE}
