{
 "title": "model_metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Inference time, usec.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_duration_us"
    },
    {
     "expr": "nv_inference_request_duration_us"
    },
    { "expr": "nv_inference_queue_duration_us" },
    {
     "expr": "nv_inference_compute_input_duration_us"
    },
    {
     "expr": "nv_inference_compute_output_duration_us"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nv_cpu_utilization" },
    { "expr": "nv_cpu_memory_total_bytes" },
    { "expr": "nv_cpu_memory_used_bytes" }
   ]
  },
  {
   "title": "Data drift",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", number_of_columns, number_of_drifted_columns, dataset_drift FROM test LIMIT 50 "
    }
   ]
  }
 ]
}