apiVersion: 1
groups:
    - orgId: 1
      name: default
      folder: Alerts
      interval: 1m
      rules:
        - uid: edb37ce2-fe6f-4d8c-bff1-ff2c02d84a3c
          title: Data drift alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: PCC52D03280B7034C
              model:
                editorMode: code
                format: table
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: 'SELECT count(CASE WHEN dataset_drift THEN 1 END) FROM test '
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
                table: test
            - refId: B
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: e8c763cd-b9e8-4933-ab47-58680d7821fa
          panelId: 3
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: e8c763cd-b9e8-4933-ab47-58680d7821fa
            __panelId__: "3"
            description: Data drift occurred
            summary: Data drift occurred
          isPaused: false
