name: build

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*'
jobs:
  build_conda_pack:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build_conda_pack
      run: make build_conda_pack
    - name: publish
      uses: actions/upload-artifact@v3
      with:
          name: triton_models
          path: ./src/deploy/triton_models
          retention-days: "2"
  run_unit_tests:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'
    - name: setup
      run: |
          sudo apt-get install -y ffmpeg make ca-certificates curl gnupg
          pip install -r requirements.txt
    - name: unit_tests
      run: make unit_tests
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
