name: build

on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'
    - name: setup
      run: make setup
    - name: unit_tests
      run: make unit_tests
    - name: get_codecov
      run: echo "COVERAGE=`jq .totals.percent_covered cov.json | cut -d. -f1`" >> $GITHUB_ENV
    - name: codecov_badge
      uses: Schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: c1336d0706263813a2eabbb344302bc1
        filename: codecov.json
        label: Coverage
        message: ${{ env.COVERAGE }}
        color: "hsl(30, 100%, 40%)"
