name: build

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*'
jobs:
  build_conda_pack:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build_conda_pack
      run: make build_conda_pack
    - name: publish
      uses: actions/upload-artifact@v3
      with:
        name: triton_models
        path: ./src/deploy/triton_models
        retention-days: "2"
  build_dev_image:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: log_in_dockerhub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build_dev_image
      run: |
        docker compose -f docker-compose.yaml build audioprocessor_dev
        docker tag audioprocessor_dev:v1.0.0 ayeffkay/mlops_zoomcamp_project:audioprocessor
  run_unit_tests:
    runs-on: ubuntu-20.04
    container:
      image: ayeffkay/mlops_zoomcamp_project:audioprocessor
      volumes:
        - src:/root/src
        - tests:/root/tests
    steps:
    - name: unit_tests
      run: |
        pip install pytest pytest-cov
        echo pwd
        echo `ls src`
    - name: upload_coverage_reports
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
